"""Initial migration

Revision ID: 213719391e09
Revises:
Create Date: 2026-01-26 16:34:34.381802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '213719391e09'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Расширение должно существовать до создания колонок типа vector,
    # иначе миграция падает на чистой базе. В Docker его же создаёт
    # init-db.sql, но при локальной установке выполнить это некому.
    # Требует прав суперпользователя: pgvector не помечен как trusted.
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=True),
    sa.Column('inn', sa.String(length=20), nullable=True),
    sa.Column('kpp', sa.String(length=20), nullable=True),
    sa.Column('ogrn', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('contacts', sa.Text(), nullable=True),
    sa.Column('director', sa.String(length=255), nullable=True),
    sa.Column('experience', sa.Text(), nullable=True),
    sa.Column('stack', sa.Text(), nullable=True),
    sa.Column('advantages', sa.Text(), nullable=True),
    sa.Column('embedding', Vector(1536), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('variables', sa.JSON(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("type IN ('proposal', 'letter', 'requirements')", name='check_valid_template_type'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_templates_company_id'), 'document_templates', ['company_id'], unique=False)
    op.create_table('exclusion_filters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('context_rule', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exclusion_filters_company_id'), 'exclusion_filters', ['company_id'], unique=False)
    op.create_table('inclusion_filters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('weight >= 1 AND weight <= 10', name='check_weight_range'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inclusion_filters_company_id'), 'inclusion_filters', ['company_id'], unique=False)
    op.create_table('skus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('synonyms', sa.JSON(), nullable=True),
    sa.Column('characteristics', sa.JSON(), nullable=True),
    sa.Column('has_ru', sa.Boolean(), nullable=False),
    sa.Column('has_ss', sa.Boolean(), nullable=False),
    sa.Column('has_gisp', sa.Boolean(), nullable=False),
    sa.Column('shelf_life_months', sa.Integer(), nullable=True),
    sa.Column('price_min', sa.Float(), nullable=True),
    sa.Column('price_max', sa.Float(), nullable=True),
    sa.Column('embedding', Vector(1536), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('price_max >= 0', name='check_price_max_positive'),
    sa.CheckConstraint('price_max IS NULL OR price_min IS NULL OR price_max >= price_min', name='check_price_range'),
    sa.CheckConstraint('price_min >= 0', name='check_price_min_positive'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skus_category'), 'skus', ['category'], unique=False)
    op.create_index(op.f('ix_skus_company_id'), 'skus', ['company_id'], unique=False)
    op.create_index(op.f('ix_skus_is_active'), 'skus', ['is_active'], unique=False)
    op.create_table('tenders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('tender_number', sa.String(length=50), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('customer', sa.String(length=500), nullable=True),
    sa.Column('price', sa.String(length=100), nullable=True),
    sa.Column('deadline', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('embedding', Vector(1536), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('risk_flags', sa.JSON(), nullable=True),
    sa.Column('missing_items', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("category IN ('target', 'prospective', 'possible', 'low', NULL)", name='check_valid_category'),
    sa.CheckConstraint("status IN ('new', 'viewed', 'participating', 'won', 'lost')", name='check_valid_status'),
    sa.CheckConstraint('relevance_score IS NULL OR (relevance_score >= 0 AND relevance_score <= 100)', name='check_relevance_range'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenders_company_id'), 'tenders', ['company_id'], unique=False)
    op.create_index(op.f('ix_tenders_created_at'), 'tenders', ['created_at'], unique=False)
    op.create_index(op.f('ix_tenders_status'), 'tenders', ['status'], unique=False)
    op.create_index(op.f('ix_tenders_tender_number'), 'tenders', ['tender_number'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('notification_threshold', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_company_id'), 'users', ['company_id'], unique=False)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('tender_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tender_id', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('participated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("result IN ('won', 'lost')", name='check_valid_result'),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tender_history_tender_id'), 'tender_history', ['tender_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tender_history_tender_id'), table_name='tender_history')
    op.drop_table('tender_history')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_index(op.f('ix_users_company_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tenders_tender_number'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_status'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_created_at'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_company_id'), table_name='tenders')
    op.drop_table('tenders')
    op.drop_index(op.f('ix_skus_is_active'), table_name='skus')
    op.drop_index(op.f('ix_skus_company_id'), table_name='skus')
    op.drop_index(op.f('ix_skus_category'), table_name='skus')
    op.drop_table('skus')
    op.drop_index(op.f('ix_inclusion_filters_company_id'), table_name='inclusion_filters')
    op.drop_table('inclusion_filters')
    op.drop_index(op.f('ix_exclusion_filters_company_id'), table_name='exclusion_filters')
    op.drop_table('exclusion_filters')
    op.drop_index(op.f('ix_document_templates_company_id'), table_name='document_templates')
    op.drop_table('document_templates')
    op.drop_table('companies')
    # ### end Alembic commands ###
